# Generated by Django 4.1.4 on 2022-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_image', models.ImageField(help_text='big picture for slider', upload_to=None, verbose_name='Large Image')),
                ('small_image', models.ImageField(help_text='small picture for slider', upload_to=None, verbose_name='Small Image')),
                ('shape', models.ImageField(help_text='sliding figure behind the slider', upload_to=None, verbose_name='Shape')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('colorful_hood', models.CharField(max_length=20, verbose_name='Color hood')),
                ('color_of_the_title', models.CharField(default='#606da6', max_length=20, verbose_name='color of the title')),
                ('slogan', models.CharField(max_length=20, verbose_name='Slogan')),
                ('tagline', models.CharField(help_text='a slogan on the slider', max_length=50, verbose_name='Tagline')),
                ('description2', models.CharField(max_length=40, verbose_name='Descripton 2')),
                ('slider_background_color', models.CharField(default='#f0f5f9', max_length=10, verbose_name='slider background color')),
            ],
        ),
    ]
