# Generated by Django 4.1.4 on 2022-12-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_background_color',
            field=models.CharField(default='#f0f5f9', max_length=10, verbose_name='slider background color'),
        ),
    ]
