# Generated by Django 4.1.4 on 2022-12-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider_slider_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description1',
        ),
    ]
