# Generated by Django 4.1.4 on 2022-12-11 15:22

from django.db import migrations, models
import userauth.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_adress_billingadress_role_kullanicilar_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[userauth.models.profile.validate_phone_number], verbose_name='Mobile Phone'),
        ),
    ]
