# Generated by Django 4.1.4 on 2022-12-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Opsiyon Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Product_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.option', verbose_name='Opsiyon')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='Stok Kodu')),
                ('stock_quantity', models.IntegerField(verbose_name='Stok Sayısı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
            ],
        ),
        migrations.CreateModel(
            name='Variation_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.products', verbose_name='Ürün Adı')),
                ('product_options_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_options', verbose_name='Urun Opsiyonlarından Seçiniz')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sku', verbose_name='Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='Option_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Opiyon Değeri')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='product.option')),
            ],
        ),
    ]
