# Generated by Django 4.1.4 on 2022-12-16 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_option_product_options_sku_variation_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_options',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='ürün seç '),
        ),
    ]
