# Generated by Django 4.1.4 on 2022-12-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_options_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation_values',
            name='product_options_id',
            field=models.ForeignKey(limit_choices_to={'product__id': 1}, on_delete=django.db.models.deletion.CASCADE, to='product.product_options', verbose_name='Urun Opsiyonlarından Seçiniz'),
        ),
    ]
