# Generated by Django 4.1.4 on 2022-12-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_variation_values_product_options_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option_value',
            name='options',
        ),
        migrations.RemoveField(
            model_name='product_options',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_options',
            name='product_options',
        ),
        migrations.RemoveField(
            model_name='variation_values',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variation_values',
            name='product_options_id',
        ),
        migrations.RemoveField(
            model_name='variation_values',
            name='sku_id',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Option_value',
        ),
        migrations.DeleteModel(
            name='Product_options',
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
        migrations.DeleteModel(
            name='Variation_values',
        ),
    ]
