# Generated by Django 4.1.4 on 2022-12-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_option_value_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='orpsiyon adi ')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU Code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('stock', models.IntegerField(verbose_name='Stok Sayısı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='ürün seçiniz ')),
            ],
        ),
        migrations.CreateModel(
            name='Product_variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=' Opsiyon Değeri ')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.option', verbose_name='Opsiyon Değeri')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='urun seçin')),
            ],
        ),
        migrations.CreateModel(
            name='Product_variation_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variations_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_variations', verbose_name='Ürün Varyasyonu seçiniz')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sku', verbose_name='Sku Seçin')),
            ],
        ),
    ]
