# Generated by Django 4.1.4 on 2022-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_option_sku_product_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variation_options',
            name='product_variations_id',
        ),
        migrations.AddField(
            model_name='product_variation_options',
            name='product_variations_id',
            field=models.ManyToManyField(to='product.product_variations', verbose_name='Ürün Varyasyonu seçiniz'),
        ),
    ]
