# Generated by Django 4.1.4 on 2022-12-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_variation_options_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variation_options',
            name='name',
            field=models.CharField(default='asdasd', max_length=50, verbose_name='Ürün için varyasyon ismi '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_variation_options',
            name='product_variations_id',
            field=models.ManyToManyField(related_name='tum_varyasyon', to='product.product_variations', verbose_name='Ürün Varyasyonu seçiniz'),
        ),
    ]
