# Generated by Django 4.1.4 on 2022-12-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_option_value_remove_product_variations_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variations',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.option_value', verbose_name='Opsiyon Değeri'),
        ),
        migrations.AlterField(
            model_name='product_variations',
            name='option_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.option', verbose_name=' Opsiyon'),
        ),
    ]
