# Generated by Django 4.1.4 on 2022-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_variations_option_option_value_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variation_options',
            name='product_variations_id',
            field=models.ManyToManyField(related_name='tum_varyasyon', to='product.option_value', verbose_name='Ürün Varyasyonu seçiniz'),
        ),
    ]
