# Generated by Django 4.1.4 on 2022-12-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_variation_options_product_variations_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='product',
        ),
    ]
