# Generated by Django 4.1.4 on 2022-12-18 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_sku_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_value',
            name='name',
            field=models.CharField(max_length=50, verbose_name='orpsiyon adi'),
        ),
        migrations.AlterField(
            model_name='product_variation_options',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sku', unique=True, verbose_name='Sku Seçin'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='product.tags', verbose_name='Etiketler'),
        ),
    ]
