# Generated by Django 4.1.4 on 2022-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_image',
            options={'verbose_name': 'Ürünler Resimi', 'verbose_name_plural': 'Ürünler Resimleri'},
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(upload_to='2022/12/Product'),
        ),
    ]
