# Generated by Django 4.1.4 on 2022-12-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_value',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi'),
        ),
        migrations.AlterField(
            model_name='option_value',
            name='name',
            field=models.CharField(max_length=50, verbose_name='opsiyon adi'),
        ),
    ]
