# Generated by Django 4.1.4 on 2022-12-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_option_value_is_active_alter_option_value_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi'),
        ),
    ]
