# Generated by Django 4.1.4 on 2022-12-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_option_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_value',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optiyon_value', to='product.option', verbose_name='Option'),
        ),
    ]
