# Generated by Django 4.1.4 on 2022-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_products_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_variations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('Fiziksel ürün', 'P'), ('Dijital Ürün', 'D')], help_text='P fiziksel D djital ürünü temsil eder', max_length=20, verbose_name='Ürün Tipi'),
        ),
    ]
