# Generated by Django 4.1.4 on 2022-12-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_products_is_variations_alter_products_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sku_code',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
